### ISSUE TITLE
Type Inference Issue with Eden Treaty Group Endpoints in v1.3.0

### ISSUE THREAD

**Issue by myparsleycat** [elysiajs/elysia#1189]
### What version of Elysia is running?

1.3.0

### What platform is your computer?

Microsoft Windows NT 10.0.26100.0 x64

### What steps can reproduce the bug?

In v1.3.0, when using Eden Treaty with grouped endpoints (where an endpoint is defined within a group), TypeScript fails to properly infer the type for the endpoint.

```
  .group('/users', (app) => app
    .post('/', async ({ body }) => {
      // Create user endpoint
      return { success: true, userId: 1 };
    })
    .get('/:id', async ({ params }) => {
      // Get user by ID endpoint
      return { id: params.id, name: 'John Doe' };
    })
  )
```

Client-side consumption attempt:
```
// Client-side with Eden Treaty
// This works in v1.2.x with .index but should work without .index in v1.3.0
const createUser = await client.users.post(
  { name: 'John Doe', email: 'john@example.com' }
);
```

### What is the expected behavior?

TypeScript should correctly infer the type for grouped endpoints when called without the .index accessor
### What do you see instead?

TypeScript produces the following error:
`Property 'post' does not exist on type '((params: { id: string | number; }) => { ...; }) & { ...; }'.ts(2339)`

However, if I move the endpoint outside of the group structure:
```
// Server configuration modified
.post('/users', async ({ body }) => {
  // Create user endpoint
  return { success: true, userId: 1 };
})
.get('/users/:id', async ({ params }) => {
  // Get user by ID endpoint
  return { id: params.id, name: 'John Doe' };
})
```

Then TypeScript correctly infers the type for the client call

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by Kapsonfire-DE** [comment]
Isnt limited to eden treaty.
The dts Plugin suffers same issue @rayriffy 

https://discord.com/channels/1044804142461362206/1367996324087074818

**Comment by edenstrom** [comment]
I noticed that it works, if the nested route is `""` and not `"/"`.

```typescript
 .group('/users', (app) => app
    .post('', async ({ body }) => {
      // Create user endpoint
      return { success: true, userId: 1 };
    })
    .get('/:id', async ({ params }) => {
      // Get user by ID endpoint
      return { id: params.id, name: 'John Doe' };
    })
  )
```

**Comment by SaltyAom** [comment]
Should have been fixed updating to [1.3.1](https://github.com/elysiajs/elysia/releases/tag/1.3.1).

Let me know if this works.

**Comment by myparsleycat** [comment]
Confirmed fixed in 1.3.1

**Comment by mjjabarullah** [comment]
I am still facing this issue. anything have i missed? i am using 1.3.1

**Comment by myparsleycat** [comment]
> [@myparsleycat](https://github.com/myparsleycat) I am still facing this issue. anything have i missed? i am using 1.3.1. Only working when i move out of group

Have you tried removing node_modules and trying again? I'm currently working with elysia 1.3.1 and @elysiajs/eden 1.3.2 and not experiencing this issue

**Comment by mjjabarullah** [comment]
I have removed node_modules tried agian.  same elysia 1.3.1 and eden 1.3.2 versions i am using. Can you try removing node_modules once again and check?

**Comment by myparsleycat** [comment]
That's strange. I just reinstalled node_modules and restarted vscode but there's no problem
```
.group('/share', (app) => app
.group('/permission/', (app) => app
.get('/', async ({ status, session, params: { id } }) => {}
```
`const { data } = await elysia.api.akasha.content.share.permission({ id: 'asdf' }).get();`

Type inference is working

**Comment by mjjabarullah** [comment]
I am using group function with params defined

![Image](https://github.com/user-attachments/assets/3d219f56-1ccb-4c9b-8d9e-169cbc868651)

**Comment by myparsleycat** [comment]
![Image](https://github.com/user-attachments/assets/00e60367-05be-4612-8334-93864431f630)

![Image](https://github.com/user-attachments/assets/807d47c1-ec31-4baf-8f9d-e5bf00d339a0)

"I've recreated and tested a similar scenario, and it appears to be functioning normally."

**Comment by mjjabarullah** [comment]
I will try again removing node_modules and get back to you. Thanks for your quick replies 🙂

**Comment by mjjabarullah** [comment]
> ![Image](https://github.com/user-attachments/assets/00e60367-05be-4612-8334-93864431f630)
> 
> ![Image](https://github.com/user-attachments/assets/807d47c1-ec31-4baf-8f9d-e5bf00d339a0)
> 
> I made something similar to test it out, and it works fine for me

its working now i made a mistake while returning the app from the group's function 
i has added app =>{ 
  app.get()
  return app;
}
this causes the type inference error. after changing this to 
app => app.get(); this 
Now it is working fine.

@myparsleycat thanks for the sample code
