### ISSUE TITLE
error at start

### ISSUE THREAD

**Issue by alphaleadership** [elysiajs/elysia#1627]
### What version of Elysia is running?

├── elysia@1.4.19

### What platform is your computer?

Microsoft Windows NT 10.0.26100.0 x64

### What environment are you using

bun 1.3.1 node v24.9.0

### Are you using dynamic mode?

no change 

### What steps can reproduce the bug?

just start the serveur 

### What is the expected behavior?

server run 

### What do you see instead?

error

### Additional information

410 | 			this.telemetry = {
411 | 				stack: new Error().stack
412 | 			}
413 | 	}
414 | 
415 | 	'~adapter': ElysiaAdapter
       ^
TypeError: t.Module is not a function. (In 't.Module({})', 't.Module' is undefined)
      at new Elysia (D:\partagesio\node_modules\elysia\src\index.ts:415:2)
      at D:\partagesio\index.js:237:13

Bun v1.3.1 (Windows x64)

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

yes

**Comment by alphaleadership** [comment]
@SaltyAom

**Comment by SaltyAom** [comment]
If you use node and pnpm, sometimes it doesn't install peer dependencies automatically which make you have to install it yourself

pnpm add @sinclair/typebox exact-mirror

**Comment by mrctrifork** [comment]
@SaltyAom I am using bun and facing the same issue when upgrading elysia from 1.2 to 1.4

**Comment by DerTimonius** [comment]
same issue here after upgrading to `1.4.22`. all peer dependencies are installed. running Elysia through wrangler, which I also updated. tried it with both the experimental cloudflare worker adapter and without, both show the same error: `t.Module is not a function`

**Comment by mrctrifork** [comment]
@DerTimonius you must install typebox manually to the version indicated by package.json in the repo

**Comment by DerTimonius** [comment]
@mrctrifork I already tried to explicitly add typebox and exact-mirror, but with the same result. I wouldn't be surprised if this is a problem of wrangler?

Version `1.4.21` works though!
