### ISSUE TITLE
Module lookup issue

### ISSUE THREAD

**Issue by Aniketkhote** [elysiajs/elysia#1951]
### What version of Elysia is running?

2.0.0-exp.60

### What platform is your computer?

Linux 7.0.0-28-generic x86_64 unknown

### What environment are you using

Bun 1.3.14

### What steps can reproduce the bug?

1. Create new project
2. Run dev server

### What do you see instead?

error: Cannot find module 'typebox/type' from '/home/aniket/Desktop/bungres-team/example/node_modules/elysia/dist/type/index.mjs'

### Have you try removing the `node_modules` and `bun.lock` and try again yet?

yes

**Comment by LanXa7** [comment]
I've also encountered this situation. Additionally, I noticed that the openapi package has something odd about it — I'm not sure whether it should be @elysia/openapi or @elysiajs/openapi. 

<img width="3096" height="2456" alt="Image" src="https://github.com/user-attachments/assets/71a06f4f-8d0e-4716-90d0-840d55a581ee" />

**Comment by rohit-jsfreaky** [comment]
I reproduced this with Bun 1.3.14 and a minimal project using only `elysia@2.0.0-exp.60`. That release marks `typebox` optional even though its runtime bundle imports `typebox/type`, so the import fails. The same minimal project works with `elysia@2.0.0-exp.62`, where `typebox` is no longer optional and Bun installs it. Upgrading to `2.0.0-exp.62` resolves the reported failure.

**Comment by LanXa7** [comment]
I reproduced this with Bun 1.3.14 and a minimal project using only `elysia@2.0.0-exp.60`. That release marks `typebox` optional even though its runtime bundle imports `typebox/type`, so the import fails. The same minimal project works with `elysia@2.0.0-exp.62`, where `typebox` is no longer optional and Bun installs it. Upgrading to `2.0.0-exp.62` resolves the reported failure.

The error I actually encountered was due to an issue with openapi:  Cannot find module '../node_modules/typebox/build/type/script/script.mjs' from '/Users/lanxa7/personal_project/babel-power/node_modules/@elysia/openapi/dist/gen/index.mjs' 

elysiajs version : [2.0.0-beta.4](https://www.npmjs.com/package/elysia/v/2.0.0-beta.4)
elysiajs openapi version : [2.0.0-beta.1](https://www.npmjs.com/package/@elysia/openapi/v/2.0.0-beta.1)

**Comment by rohit-jsfreaky** [comment]
Thanks for the details. That looks like a separate issue in the old `@elysiajs/openapi` beta package, rather than the `elysia@2.0.0-exp.60` dependency issue in this report. Could you open a separate issue with a minimal reproduction and those exact package versions?

**Comment by LanXa7** [comment]
> Thanks for the details. That looks like a separate issue in the old `@elysiajs/openapi` beta package, rather than the `elysia@2.0.0-exp.60` dependency issue in this report. Could you open a separate issue with a minimal reproduction and those exact package versions?

Sure, I've opened a new issue along with the repository link for the minimal reproduction, and I've tagged you in it.
