### ISSUE TITLE
macro resolve returning a union of object shapes infers route context as `never` (regression in 1.4.25)

### ISSUE THREAD

**Issue by qbitdoge** [elysiajs/elysia#1891]
### What version of Elysia is running?

```
elysia@1.4.25
```

Last known-good version: `elysia@1.4.24`. Reproduces on `1.4.25` through `1.4.28`.

### What platform is your computer?

```
Darwin arm64
```

### What environment are you using

This is a **type-level** regression — it reproduces under `tsc` alone, no runtime involved. Confirmed under both:

- TypeScript `tsc` 5.9.3
- `@typescript/native-preview` (`tsgo`)

### Are you using dynamic mode?

No. Default AOT (no `aot: false`).

### What steps can reproduce the bug?

When a `macro`'s `resolve` returns a **union of two or more object shapes** (TypeScript infers the resolve return type as `A | B` of different object types), any route that enables the macro and reads the resolved context receives `never` instead of the resolved properties. Started in `1.4.25`; clean in `1.4.24`.

`async`, returning `status(...)` from some branches, and `.as("scoped")` are **not** required to trigger it. The single necessary ingredient is that the `resolve` return type is a union of object shapes.

Minimal reproduction (`repro.ts`):

```ts
import { Elysia } from "elysia";

const plugin = new Elysia({ name: "plugin" })
  .macro({
    withUser: {
      resolve() {
        // Inferred return type is a UNION of two object shapes:
        //   { user: { id: string } } | { user: { id: string }; admin: boolean }
        if (Math.random() > 0.5) return { user: { id: "a" } };
        return { user: { id: "b" }, admin: true };
      },
    },
  });

const app = new Elysia()
  .use(plugin)
  .get("/", ({ user }) => user.id, { withUser: true });
//                ^^^^
// 1.4.24: typed as { id: string }
// 1.4.25: context is `never` -> TS2339 below
```

`tsconfig.json` (`strict`, bundler resolution):

```json
{
  "compilerOptions": {
    "strict": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "target": "ESNext",
    "noEmit": true,
    "skipLibCheck": true
  }
}
```

Run:

```
npm i elysia@1.4.24 && npx tsc -p tsconfig.json   # clean
npm i elysia@1.4.25 && npx tsc -p tsconfig.json   # errors
```

#### Likely cause

The `1.4.25` changelog lists two macro fixes — "Macro with conflict literal value per status" and "Recursive macro with conflict value per status". These appear to have introduced the regression: reconciling multiple `resolve` return values now collapses a multi-shape resolve union to `never` rather than unioning the shapes.

### What is the expected behavior?

The consumer's context should be the union of the resolved shapes, i.e. `{ user: { id: string } } | { user: { id: string }; admin: boolean }`, so the common `user` property is accessible and typed. This is the behavior in `1.4.24` and earlier.

### What do you see instead?

The route context is inferred as `never`, so accessing any resolved property fails to type-check:

```
repro.ts(...): error TS2339: Property 'id' does not exist on type 'never'.
```

In a larger codebase this cascades: every route consuming such a macro produces one TS2339 per accessed property.

### Additional information

- Bisected to `1.4.25`. `1.4.24` is the last good release; `1.4.25`–`1.4.28` all reproduce.
- Reproduces under both `tsc` 5.9.3 and `@typescript/native-preview` (`tsgo`) — not compiler-specific.
- Deterministic across repeated runs.
- Tested in a fresh project with only `elysia` + `typescript` installed; not a stale-`node_modules` artifact.
