### ISSUE TITLE
derive method doesn't work as a plugin

### ISSUE THREAD

**Issue by nodirbekrajaboff** [elysiajs/elysia#566]
### What version of Elysia.JS is running?

1.0.7

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Property 'userDevice' does not exist on type '{ body: { username: string; password: string; }; query: Record<string, string | undefined>; params: never; headers: Record<string, string | undefined>; cookie: Record<string, Cookie<...>>; ... 5 more ...; jwt: { ...; }; }'.

// device-detect.ts
![image](https://github.com/elysiajs/elysia/assets/119718499/609d37f2-dca4-4b39-8b30-c09c837fa317)

// authentication.ts
![image](https://github.com/elysiajs/elysia/assets/119718499/cc4c6996-7dec-485f-9f3d-fa9737cf15f4)

// sign-in-route.ts
![image](https://github.com/elysiajs/elysia/assets/119718499/aa2bb3f1-7d0e-48ad-8052-a5bf5dc53ea6)

### What is the expected behavior?

I want to get user device to store information about user device. But derive method doesn't work as a plugin

**Comment by kravetsone** [comment]
https://github.com/elysiajs/elysia/issues/513

Specify derive as global

**Comment by JZubero** [comment]
Continues to happen for me with v1.0.9 and the `{ as: 'global' }` config for `derive()`. I can only get rid of the red squiggly lines if the plugin is included (via `app.use()`) in every instance that should be able to access the derived properties.

**Comment by kidqueb** [comment]
Tried to quickly reproduce it with something simple but this worked fine in 1.0.11. Can you make something with `{ as: 'global' }` failing?

```typescript
const deviceDetect = new Elysia({ name: "device-detect" })
  .derive({ as: "global" }, ({ request }) => {
    let userAgent = request.headers.get('user-agent');
    return { userAgent }
  });

const auth = new Elysia({ name: "auth" })
  .use(deviceDetect);

const controller = new Elysia()
  .use(auth)
  .get('/', ({ userAgent }) => userAgent)
```

**Comment by SaltyAom** [comment]
Close as #513 and no further discussion for 2 weeks.
Feels free to ping me to reopen this issue if necessary.

**Comment by russism** [comment]
This seems to work for me:

```typescript
// auth.ts
export const account = new Elysia()
	.use(bearer())
	.use(access)
	.derive({ as: 'scoped' }, async ({
		bearer, jwtAccess,
	}) => {
		if (!bearer)
			throw new ForbiddenError('Unauthorized.')
		
		const access = await jwtAccess.verify(bearer)
		if (!access)
			throw new ForbiddenError('Unauthorized.')

		return {
			account: JSON.parse(access.id),
		}
	})

// page.ts
export default new Elysia({ prefix: '/page' })
	.get('/', async ({ account }) => {
		console.log(account)
		return await Page.fetch(account)
	})
	
// api.ts
import { account } from '@/auth'
import page from './page'
	
export default new Elysia({ prefix: '/api' })
	.use(account)
	.use(page)
```

But for some reason i just couldn't get rid of the red squiggly in vscode under `({ account })` in `page.ts`
