### ISSUE TITLE
Elysia 2.0.0-beta.6 - Vercel - Error: Cannot find module 'typebox/type'

### ISSUE THREAD

**Issue by codler** [elysiajs/elysia#1973]
### What version of Elysia is running?

Elysia 2.0.0-beta.6

### What environment are you using

Vercel

### Are you using dynamic mode?

no

### What steps can reproduce the bug?

Make a GET request in Vercel env

### What is the expected behavior?

no error

### What do you see instead?

Im getting this error message in Vercel when making a request
```
Error: Cannot find module 'typebox/type'
Require stack:
- /var/task/node_modules/elysia/dist/type/typebox-type.mjs
    at <unknown> (../../opt/rust/nodejs.js:2:14275)
    at Module.vo (../../opt/rust/nodejs.js:2:14653)
    at e.<computed>.ut._load (../../opt/rust/nodejs.js:2:14245) {
code: "MODULE_NOT_FOUND",
requireStack: [
0: "/var/task/node_modules/elysia/dist/type/typebox-type.mjs"
]
}

### Additional information

_No response_

### Have you try removing the `node_modules` and `bun.lock` and try again yet?

_No response_

**Comment by codler** [comment]
Hope this gets fixed in #1873

**Comment by codler** [comment]
Also getting 
```
Error: require() of ES Module /var/task/node_modules/typebox/build/type/index.mjs from /var/task/node_modules/elysia/dist/type/typebox-type.mjs not supported.
Instead change the require of /var/task/node_modules/typebox/build/type/index.mjs to a dynamic import() which is available in all CommonJS modules.
    at <unknown> (../../opt/rust/nodejs.js:2:14275)
    at Module.vo (../../opt/rust/nodejs.js:2:14653)
    at e.<computed>.ut._load (../../opt/rust/nodejs.js:2:14245) { code: "ERR_REQUIRE_ESM" }

**Comment by bhupinder759** [comment]
I would like to take this up and investigate the TypeBox import resolution for Node/Vercel runtimes. Please assign this to me.

**Comment by ymdggap4t** [comment]
We hit the same thing on Vercel. Here is a minimal reproduction, the version that introduced it, and a second symptom that shows up even when the module *does* resolve.

## Root cause

Since `2.0.0-beta.3`, `t` is a Proxy and `src/type/typebox-type.ts` loads TypeBox on first use through a synchronous runtime require:

```js
const req = import.meta.require ?? globalThis.process?.getBuiltinModule?.('module')?.createRequire(import.meta.url)
return { type: req('typebox/type'), system: req('typebox/system') }
```

No bundler can see through `createRequire`, so **TypeBox silently falls out of the bundle** and only the runtime require survives. The bundler reports success; the artifact is broken.

## Bisect

Empty project, `bun add elysia@<version> typebox`, entry is `import { t } from 'elysia'; t.Literal('a')`, built with `bun build ./index.ts --target=node --format=esm --outfile=out.mjs`, run with `node out.mjs`.

| elysia | bundle | `require('typebox/type')` left in bundle | first `t.*` (min of 7) | run from a dir with no reachable `node_modules` |
| --- | --- | --- | --- | --- |
| 2.0.0-beta.1 | 564 KB | no | 0.0 ms | ok |
| 2.0.0-beta.2 | 564 KB | no | 0.0 ms | ok |
| 2.0.0-beta.3 | 160 KB | **yes** | **131.5 ms** | **crash** |
| 2.0.0-beta.4 | 160 KB | yes | 140.3 ms | crash |
| 2.0.0-beta.5 | 160 KB | yes | 139.6 ms | crash |
| 2.0.0-beta.6 | 160 KB | yes | 138.8 ms | crash |

`beta.3` is where it starts. The 400 KB the bundle loses is TypeBox falling out of it.

Environment: Node v24.19.0, Bun 1.4.0, Linux x64.

## Reproduction

```sh
mkdir repro && cd repro
echo '{ "name": "repro", "private": true, "type": "module" }' > package.json
bun add elysia@2.0.0-beta.6 typebox
cat > index.ts <<'EOF'
import { t } from 'elysia'

const start = performance.now()
t.Literal('a')
console.log(`first t.*: ${(performance.now() - start).toFixed(1)}ms`)
EOF
bun build ./index.ts --target=node --format=esm --outfile=out.mjs

node out.mjs                    # first t.*: ~138ms

mkdir -p /tmp/iso && cp out.mjs /tmp/iso/ && cd /tmp/iso
node out.mjs                    # Error: Cannot find module 'typebox/type'
```

## Symptom 1 — the bundle cannot start where `node_modules` is not reachable

This is the crash in this issue. It is easy to miss locally, because a bundle sitting anywhere inside your repo still resolves `typebox` by walking up to the repo's `node_modules`. Copy the same bundle one directory outside the tree — which is what a deployed serverless function looks like — and it throws on import.

On our real app (Elysia server bundled to a single file, deployed as a Vercel Node function):

- bundled without the AOT plugin → isolated import throws `Cannot find module 'typebox/type'`
- bundled with the AOT plugin → isolated import succeeds

Worth noting for the `ERR_REQUIRE_ESM` variant reported above: `typebox` is ESM-only (`"type": "module"`, `./type` → `build/type/index.mjs`). `require()` of it only works on Node ≥ 22.12 (`require(esm)`) or under Bun's `import.meta.require`. So depending on the Node version, the same code path fails two different ways — `MODULE_NOT_FOUND` when the package is not reachable, `ERR_REQUIRE_ESM` when it is reachable but the loader cannot `require` ESM.

## Symptom 2 — cold start regression, even when it resolves

When the require *does* resolve, it still costs a synchronous load of the whole TypeBox type graph at first `t.*`. Measured on our real app's bundle, same machine, `min-of-7`, two alternating rounds, `node_modules` reachable so both variants can run:

```
round 1: runtime typebox load = 283.6ms   |   statically wired = 174.3ms
round 2: runtime typebox load = 285.9ms   |   statically wired = 170.0ms
```

That is ~112 ms added to every cold start. It matched what we saw when we upgraded from `2.0.0-exp.52` to `2.0.0-beta.6`: our function's cold import went 165 ms → 284 ms.

## The AOT plugin fixes both — with two gaps

`elysia/plugin/aot/*` rewrites `type/typebox-type` to a statically imported mirror, and both symptoms disappear. For anyone landing here, the call needs the entry path:

```ts
import { resolve } from 'node:path'
import { aot } from 'elysia/plugin/aot/bun'

const entry = resolve(import.meta.dir, 'src/index.ts')

await Bun.build({
  entrypoints: [entry],
  target: 'node',
  format: 'esm',
  plugins: [aot(entry, { target: 'node' })],
})
```

Two things still bite:

1. **Nothing fails at build time.** A plain `bun build --bundle` of an Elysia app emits a bundle that looks self-contained — no external `import` statements are left, so even our own "no external imports survived" build check passed — and then dies on the first request in production. The failure only surfaces at runtime, in the deployed environment.

2. **The escape hatch requires the entry to export an Elysia app.** `aot(entry)` fails with `"<entry>" must export an Elysia app`. Code that bundles `t` without a server entry — a shared schema package, a validation-only worker, a library re-exporting `t` — has no supported way to get TypeBox wired in.

Would it be possible to make the static path the default for bundled targets, or at least fail loudly at build time when a bundler resolves `typebox-type` without the AOT plugin? Right now the only signal is a production crash.
